# The Docker image that will be used to build your app new commit
image: node:lts
# Functions that should be executed before the build script is run
before_script:
  - ":"
pages:
  environment: "test"
  script:
    - echo "test1102jtestsynca"
    
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
